main: blue.melon.corf.SpigotLoader
version: 1.0
name: CoreProtectRecordFilter
author: langua
api-version: 1.20
depend:
  - CoreProtect
libraries:
  - org.jetbrains.kotlin:kotlin-stdlib:2.0.20
commands:
  corf:
    usage: /corf or /corf reload