main: blue.melon.corf.SpigotLoader
version: ${version}
name: CoreProtectRecordFilter
author: langua
api-version: 1.20
depend:
  - CoreProtect
softdepend:
  - Multiverse-Core
libraries:
  - org.jetbrains.kotlin:kotlin-stdlib:1.9.23